version: '3.0'

services:
  rasa:
    container_name: "novo_rasa_server"
    build: 
      context: rasa_backend
    networks: ['rasa-network']
    ports:
      - "5005:5005"
      - "5055:5055"


  duckling:
    image: rasa/duckling:latest
    networks: ['rasa-network']
    ports:
      - "8000:8000"
  
  mongo:
    image: mongo
    container_name: "mongo"
    networks: ['rasa-network']
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: rasa
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:  # this service is a MongoDB UI, and is optional
    image: mongo-express
    networks: ['rasa-network']
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: rasa
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  chatbot_ui:
    container_name: "chatbot_ui"
    build: 
      context: frontend
    networks: ['rasa-network']
    ports: 
      - "3000:3000"

  nginx:
    container_name: "nginx"
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks: ['rasa-network']
    ports:
    
      - 80:80
    depends_on:
      - chatbot_ui
      - mongo
  

networks: {rasa-network: {}}
